import React from 'react';
import { Printer } from 'lucide-react';

export default function App() {
  return (
    <div className="min-h-screen bg-gray-100 py-8 print:py-0 print:bg-white font-sans text-gray-800">
      <div className="max-w-4xl mx-auto bg-white p-10 md:p-16 shadow-lg print:shadow-none print:p-0 print:max-w-full">
        {/* Header */}
        <header className="text-center mb-10">
          <h1 className="text-3xl font-bold text-[#1a343c] mb-2">Sales Director Agreement</h1>
          <p className="text-lg text-gray-600 italic">Effective Date: _________________, 20____</p>
        </header>

        <section className="mb-8 leading-relaxed text-gray-700">
          <p className="mb-4">
            This Sales Director Agreement (the "Agreement") is entered into as of the Effective Date written above, by and between <strong>VITANNIS LLC</strong>, including its affiliated agencies Nelson Advisors and Strategy Retirement & Insurance (collectively referred to as "Vitannis" or the "Agency"), and <strong>RICHARD KEEL</strong> ("Sales Director" or "Richard Keel"). Vitannis and Richard Keel may be referred to individually as a "Party" and collectively as the "Parties."
          </p>
          <div className="bg-gray-50 p-4 rounded border border-gray-200 text-sm mb-4">
            <p className="font-semibold text-gray-800 mb-1">Recitals</p>
            <p className="mb-2"><strong>WHEREAS</strong>, Vitannis is an authorized distributor of the Immediate Care Plan ("ICP") issued by Lumos Insurance (the "Carrier"); and</p>
            <p><strong>WHEREAS</strong>, Richard Keel desires to act as an independent Sales Director under the Vitannis hierarchy, personally producing business and leading a unit of sub-agents.</p>
          </div>
        </section>

        {/* Executive Summary */}
        <section className="mb-10 bg-slate-50 p-6 rounded-lg border border-slate-200 print:bg-transparent print:border-gray-300">
          <h2 className="text-xl font-bold text-[#1a343c] mb-4 print:text-gray-900">Executive Summary & Offer Overview</h2>
          <p className="mb-3 text-gray-700">
            Welcome to the Vitannis team! We are excited to partner with you. This summary outlines the basic offer, compensation structure, and operating framework for our relationship:
          </p>
          <ul className="list-disc pl-5 space-y-3 mb-4 text-gray-700">
            <li>
              <strong>Your Role & Scope of Production:</strong> You will market and sell the Immediate Care Plan (ICP) and lead a unit of licensed sub-agents. This agreement covers both your own personal sales production and the production generated by the sub-agents within your unit.
            </li>
            <li>
              <strong>Total Compensation & Unit Override (4.0% Total Pool):</strong> Total commission compensation allocated to you and your unit is <strong>4.0% of Target Premium</strong> on all placed ICP business.
              <ul className="list-circle pl-6 mt-2 space-y-1.5 text-sm text-gray-600">
                <li><strong>Sub-Agent Base Rate:</strong> Sub-agents within your unit receive a default base commission of <strong>3.0%</strong>, leaving a <strong>1.0% override</strong> to you as Sales Director.</li>
                <li><strong>Director Tier Placement:</strong> You have full discretion to place individual sub-agents at a different compensation level (e.g., 2.5%, 3.5%). Your override automatically equals the difference between 4.0% and the sub-agent's assigned level.</li>
                <li><strong>Personal Production:</strong> For policies personally written by you as Sales Director, you receive the full <strong>4.0%</strong> commission.</li>
              </ul>
            </li>
            <li>
              <strong>Support & Direct Agency Payments:</strong> Vitannis will provide limited training, product documentation, and operational resources. To keep bookkeeping simple for you, Vitannis is responsible for calculating and making commission payments directly to all parties (both to you and directly to each sub-agent in your unit).
            </li>
            <li>
              <strong>Separate Distribution Agreements:</strong> Institutional, corporate, or special distribution agreements are separate compensation arrangements and will be formally detailed on the <strong>Addendum</strong> at the end of this contract.
            </li>
          </ul>
        </section>

        {/* Terms and Conditions */}
        <section className="space-y-6">
          <h2 className="text-2xl font-bold text-[#1a343c] border-b pb-2 mb-4">Agreement Terms</h2>

          <div>
            <h3 className="text-lg font-semibold text-gray-800 mb-2">1. Independent Contractor Relationship & Limitation of Authority</h3>
            <p className="mb-2 text-gray-700 leading-relaxed">
              Richard Keel and all sub-agents within his unit are and shall remain independent contractors (1099). This Agreement does not create an employment, partnership, joint venture, or franchise relationship. Neither Party has the authority to bind the other or the Carrier. Richard Keel cannot sign contracts on behalf of Vitannis, modify insurance policies, or represent himself as an employee of Vitannis or Lumos Insurance.
            </p>
            <p className="text-gray-700 leading-relaxed text-sm">
              <em>Carrier Dependency & Precedence:</em> Lumos Insurance is not a party to this Agreement and retains absolute discretion over underwriting, policy issuance, and agent appointments. In the event of conflicting obligations, the order of precedence is: (1) Applicable Law, (2) Carrier Requirements and Procedures, (3) This Agreement, and (4) Vitannis Internal Policies.
            </p>
          </div>

          <div>
            <h3 className="text-lg font-semibold text-gray-800 mb-2">2. Unit Supervision, Approved Agents & DRLP Designation</h3>
            <p className="mb-2 text-gray-700 leading-relaxed">
              Richard Keel owns the direct relationship with his sub-agents and is solely responsible for their recruiting, supervision, mentoring, and professional conduct. All sub-agents must be duly licensed, appointed through Vitannis's hierarchy with the Carrier, and listed on <strong>Exhibit A</strong> ("Approved Agents").
            </p>
            <p className="mb-2 text-gray-700 leading-relaxed text-sm">
              <em>Flow-Down & Compliance:</em> Richard Keel shall ensure each Approved Agent complies with all provisions of this Agreement, Carrier guidelines, and applicable insurance regulations. Richard Keel shall serve as the Designated Responsible Licensed Producer (DRLP) primarily responsible for agency-level compliance.
            </p>
            <p className="text-gray-700 leading-relaxed text-sm">
              <em>Agent Removal:</em> Vitannis reserves the right to immediately suspend or remove any sub-agent from the hierarchy if ethical, legal, or compliance violations occur.
            </p>
          </div>

          <div>
            <h3 className="text-lg font-semibold text-gray-800 mb-2">3. Licensing, Training & Senior Market Compliance</h3>
            <p className="mb-2 text-gray-700 leading-relaxed">
              Prior to soliciting the ICP, the Sales Director and all sub-agents must complete all required state licensing, state Annuity CE, Carrier product training, and any limited training provided by Vitannis.
            </p>
            <p className="text-gray-700 leading-relaxed text-sm">
              <em>Senior Market Protections:</em> Because the ICP is marketed to seniors, assessing suitability, cognitive capacity, and best-interest standards is strictly mandatory. Approved Agents must maintain state-mandated Senior Sales Ethics CE credits biannually. A material compliance violation is defined as any deviation from law, Carrier requirements, or suitability standards that places a client, Carrier, or Vitannis at regulatory or financial risk.
            </p>
          </div>

          <div>
            <h3 className="text-lg font-semibold text-gray-800 mb-2">4. Marketing, Advertising & Intellectual Property</h3>
            <p className="mb-2 text-gray-700 leading-relaxed">
              Richard Keel and his unit may only use marketing materials expressly approved in writing by the Carrier and Vitannis. Creating unauthorized advertisements, making unapproved claims, or misrepresenting policy terms is strictly prohibited.
            </p>
            <p className="text-gray-700 leading-relaxed text-sm">
              <em>Trademarks:</em> Vitannis's company name, affiliated brand names, Lumos Insurance marks, and the ICP trademark may not be used in advertising, digital media, or correspondence without prior written approval.
            </p>
          </div>

          <div>
            <h3 className="text-lg font-semibold text-gray-800 mb-2">5. Compensation, Commission Splits & Payment Accounting</h3>
            <p className="mb-2 text-gray-700 leading-relaxed">
              <strong>Total Unit Compensation (4.0%):</strong> Vitannis shall allocate a total commission equal to 4.0% of the Target Premium for all ICP products placed by Richard Keel and active sub-agents in his unit.
            </p>
            <ul className="list-disc pl-5 mb-3 text-gray-700 text-sm space-y-1">
              <li><strong>Personal Production:</strong> Richard Keel earns the full 4.0% commission on his personal production.</li>
              <li><strong>Sub-Agent Production:</strong> Sub-agents receive 3.0% of Target Premium by default, leaving a 1.0% override to Richard Keel.</li>
              <li><strong>Tier Customization:</strong> Richard Keel may elect to place an individual sub-agent at an alternate commission level (designated on Exhibit A). The Sales Director's override on that agent's production shall equal 4.0% minus the agent's assigned tier.</li>
              <li><strong>Payment Schedule & Direct Disbursement:</strong> Commissions for the prior calendar month shall be calculated based on Carrier statements and disbursed by Vitannis by the 5th of each month directly to all parties (Richard Keel and sub-agents).</li>
              <li><strong>Carrier Compensation Statements:</strong> Carrier compensation statements control payouts. Any unavoidable Carrier delays will be promptly communicated to Richard Keel, with funds remitted immediately upon Vitannis receiving payment.</li>
            </ul>
            <div className="mt-4 p-4 bg-slate-50 rounded-lg border border-slate-200 print:bg-transparent print:border-gray-300">
              <p className="font-bold text-[#1a343c] mb-1 text-sm tracking-wide uppercase">
                Ongoing Override Standards (Post-Year 1)
              </p>
              <p className="text-xs text-gray-600 mb-2.5">
                To maintain uninterrupted entitlement to unit override compensation after Year 1 (12 months from the Effective Date), the Sales Director must fulfill the following continuous standards:
              </p>
              <ul className="list-disc pl-5 space-y-1.5 text-xs sm:text-sm text-gray-700">
                <li>
                  <strong>(a) Active Contract Status:</strong> Maintain an active Independent Contractor contract with Vitannis LLC as Sales Director.
                </li>
                <li>
                  <strong>(b) Active Unit Engagement:</strong> Actively engaging, mentoring, & supporting unit agent sales.
                </li>
                <li>
                  <strong>(c) Active Insurance Licensure:</strong> Continuously maintain an active insurance license in good standing with applicable state regulatory authorities.
                </li>
                <li>
                  <strong>(d) Ethical & Compliance Standards:</strong> Uphold all Vitannis LLC compliance protocols, Carrier regulations, and professional code of ethics.
                </li>
              </ul>
            </div>
          </div>

          <div>
            <h3 className="text-lg font-semibold text-gray-800 mb-2">6. Chargebacks, Rescissions & Debt Resolution</h3>
            <p className="mb-2 text-gray-700 leading-relaxed">
              Any Carrier decision to cancel, rescind, or issue a chargeback on an ICP policy is binding and requires full repayment of any commissions received by Richard Keel and the writing agent on that policy.
            </p>
            <p className="mb-2 text-gray-700 leading-relaxed text-sm">
              <em>Resolution Process:</em> Vitannis will provide written documentation within 48 hours of Carrier notification. Chargebacks will be deducted from future commission cycles by default. Richard Keel may elect to resolve the balance via direct payment; if no commissions are scheduled within ten (10) business days, direct remittance is required.
            </p>
            <p className="text-gray-700 leading-relaxed text-sm">
              <em>Default Remedies:</em> Vitannis may approve a structured repayment plan of up to three (3) installments. If a chargeback resolution is not established within 15 business days, Richard Keel waives arbitration regarding the debt, and Vitannis may pursue legal recovery directly against Richard Keel and the writing agent, and file notices with VectorOne and credit reporting agencies.
            </p>
          </div>

          <div>
            <h3 className="text-lg font-semibold text-gray-800 mb-2">7. Client Protection & Mutual Non-Solicitation</h3>
            <p className="mb-2 text-gray-700 leading-relaxed">
              Both Parties agree to protect privileged client relationships. Vitannis shall not use confidential client information to solicit or contact clients originated by Richard Keel or his unit without express consent. Reciprocally, Richard Keel and his sub-agents shall not solicit or divert clients originated directly by Vitannis.
            </p>
            <p className="text-gray-700 leading-relaxed text-sm">
              <em>Clarification:</em> This provision protects confidential information against misuse; it does not confer proprietary ownership of clients, which remains subject to Carrier rules and consumer choice under applicable law.
            </p>
          </div>

          <div>
            <h3 className="text-lg font-semibold text-gray-800 mb-2">8. Confidentiality, Data Security & Audit Rights</h3>
            <p className="mb-2 text-gray-700 leading-relaxed">
              Both Parties shall comply with HIPAA, GLBA, and all federal and state privacy statutes. Each Party must maintain reasonable administrative, technical, and physical safeguards to protect non-public personal information (PII) and protected health information (PHI). Any security incident must be reported immediately to the other Party.
            </p>
            <p className="text-gray-700 leading-relaxed text-sm">
              <em>Audit Rights:</em> Richard Keel shall maintain accurate records of ICP solicitations, applications, licenses, and training for the duration required by law and Carrier guidelines, and shall provide documentation upon request in the event of an audit.
            </p>
          </div>

          <div>
            <h3 className="text-lg font-semibold text-gray-800 mb-2">9. Errors & Omissions (E&O) Insurance & Indemnification</h3>
            <p className="mb-2 text-gray-700 leading-relaxed">
              Richard Keel must continuously maintain Errors & Omissions (E&O) insurance with minimum coverage of $1,000,000 per occurrence. Proof of coverage must be provided upon request, and Vitannis must be notified promptly of any policy cancellation, regulatory investigation, or customer complaint.
            </p>
            <p className="text-gray-700 leading-relaxed text-sm">
              <em>Mutual Indemnification:</em> Richard Keel agrees to indemnify and hold harmless Vitannis and the Carrier from claims resulting from misconduct, negligence, or breach by Richard Keel or his unit. Vitannis agrees to indemnify Richard Keel from claims arising directly from Vitannis's gross negligence or willful misconduct.
            </p>
          </div>

          <div>
            <h3 className="text-lg font-semibold text-gray-800 mb-2">10. Term, Termination & Post-Termination Obligations</h3>
            <p className="mb-2 text-gray-700 leading-relaxed">
              <em>Termination Without Cause:</em> Either Party may terminate this Agreement at any time by providing sixty (60) days' written notice.
            </p>
            <p className="mb-2 text-gray-700 leading-relaxed text-sm">
              <em>Termination For Cause:</em> Vitannis may terminate this Agreement immediately for fraud, intentional misrepresentation, license revocation, material regulatory violation, or intentional breach of Carrier rules. Minor correctable violations shall receive written notice and an opportunity to cure.
            </p>
            <p className="text-gray-700 leading-relaxed text-sm">
              <em>Post-Termination Rights:</em> Commissions continue to be payable on business issued prior to termination; chargeback liability survives indefinitely; agent appointment releases follow Carrier transfer rules and cooling-off policies; and confidentiality obligations remain binding indefinitely.
            </p>
          </div>

          <div>
            <h3 className="text-lg font-semibold text-gray-800 mb-2">11. Dispute Resolution & Governing Law</h3>
            <p className="text-gray-700 leading-relaxed text-sm">
              This Agreement shall be governed by and construed in accordance with the laws of the State of South Carolina. Except for chargeback debt collections (Section 6) and emergency injunctive relief (to protect confidential information, intellectual property, or client non-solicitation), any disputes shall be resolved through binding arbitration. Each Party bears its own legal fees and splits administrative costs equally.
            </p>
          </div>
        </section>

        {/* Signatures */}
        <section className="mt-16 pt-8 border-t print:break-inside-avoid">
          <p className="mb-8 font-medium text-gray-700">IN WITNESS WHEREOF, the Parties have executed this Sales Director Agreement as of the Effective Date.</p>
          
          <div className="grid grid-cols-1 md:grid-cols-2 gap-12">
            <div>
              <h3 className="font-bold text-[#1a343c] mb-6">VITANNIS LLC (Agency)</h3>
              <div className="border-b border-gray-400 mb-2 h-8"></div>
              <p className="text-sm text-gray-500 mb-6">Authorized Signature</p>
              
              <div className="border-b border-gray-400 mb-2 h-8"></div>
              <p className="text-sm text-gray-500 mb-6">Printed Name & Title</p>

              <div className="border-b border-gray-400 mb-2 h-8"></div>
              <p className="text-sm text-gray-500 mb-6">Notice Email Address</p>

              <div className="border-b border-gray-400 mb-2 h-8"></div>
              <p className="text-sm text-gray-500 mb-6">Date</p>
            </div>
            
            <div>
              <h3 className="font-bold text-[#1a343c] mb-6">RICHARD KEEL (Sales Director)</h3>
              <div className="border-b border-gray-400 mb-2 h-8"></div>
              <p className="text-sm text-gray-500 mb-6">Signature</p>
              
              <div className="border-b border-gray-400 mb-2 h-8"></div>
              <p className="text-sm text-gray-500 mb-6">Printed Name</p>

              <div className="border-b border-gray-400 mb-2 h-8"></div>
              <p className="text-sm text-gray-500 mb-6">Notice Email Address</p>

              <div className="border-b border-gray-400 mb-2 h-8"></div>
              <p className="text-sm text-gray-500 mb-6">Date</p>
            </div>
          </div>
        </section>

        {/* Exhibit A */}
        <section className="mt-16 print:break-before-page">
          <h2 className="text-2xl font-bold text-[#1a343c] border-b pb-2 mb-4 text-center">EXHIBIT A: Authorized Approved Agents</h2>
          <p className="text-sm italic text-gray-600 mb-2 text-center">
            This schedule lists appointed sub-agents within Richard Keel's unit authorized to market the ICP product.
          </p>
          <p className="text-xs text-center text-gray-500 mb-6">
            Active DRLP: <strong>Richard Keel</strong> | NPN / Agent #: ____________________
          </p>
          
          <div className="overflow-x-auto">
            <table className="w-full border-collapse border border-gray-300 text-sm table-fixed">
              <thead>
                <tr className="bg-gray-100 print:bg-gray-200 text-gray-800">
                  <th className="border border-gray-300 p-2 text-left w-[22%]">Agent Name</th>
                  <th className="border border-gray-300 p-2 text-left w-[14%]">License #</th>
                  <th className="border border-gray-300 p-2 text-left w-[14%]">Agent # / NPN</th>
                  <th className="border border-gray-300 p-2 text-center w-[11%]">Commission</th>
                  <th className="border border-gray-300 p-2 text-center w-[12%] leading-tight">Effective<br />Date</th>
                  <th className="border border-gray-300 p-2 text-left w-[27%]">Email</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td className="border border-gray-300 p-2.5 font-semibold text-gray-900">Bob McGee</td>
                  <td className="border border-gray-300 p-2.5"></td>
                  <td className="border border-gray-300 p-2.5"></td>
                  <td className="border border-gray-300 p-2.5 text-center font-medium text-gray-800">3.0%</td>
                  <td className="border border-gray-300 p-2.5 text-center text-gray-800 font-medium">09/18/26</td>
                  <td className="border border-gray-300 p-2.5"></td>
                </tr>
                {[2, 3, 4, 5].map((row) => (
                  <tr key={row}>
                    <td className="border border-gray-300 p-2.5 h-10"></td>
                    <td className="border border-gray-300 p-2.5"></td>
                    <td className="border border-gray-300 p-2.5"></td>
                    <td className="border border-gray-300 p-2.5 text-center text-gray-400">3.0%</td>
                    <td className="border border-gray-300 p-2.5 text-center"></td>
                    <td className="border border-gray-300 p-2.5"></td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
          <p className="text-xs text-gray-500 italic mt-3">
            * Note: Default sub-agent commission is 3.0%. If Richard Keel elects to place a sub-agent at an alternate commission level, the agreed percentage shall be marked in the Commission column above, and Richard Keel's override shall equal 4.0% minus that rate.
          </p>
        </section>

        {/* Exhibit B */}
        <section className="mt-16 print:break-before-page">
          <h2 className="text-2xl font-bold text-[#1a343c] border-b pb-2 mb-4 text-center">EXHIBIT B: Commission Schedule</h2>
          
          <div className="bg-gray-50 p-6 rounded-lg border border-gray-200 print:bg-transparent print:border-gray-300">
            <h3 className="font-bold text-lg text-gray-900 mb-4">Immediate Care Plan (ICP) Compensation Summary</h3>
            
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-6">
              <div className="bg-white p-4 rounded border border-gray-200">
                <p className="text-xs font-semibold text-gray-500 uppercase tracking-wider mb-1">Product</p>
                <p className="font-bold text-gray-800">Immediate Care Plan (ICP)</p>
                <p className="text-xs text-gray-500">Issued by Lumos Insurance</p>
              </div>
              <div className="bg-white p-4 rounded border border-gray-200">
                <p className="text-xs font-semibold text-gray-500 uppercase tracking-wider mb-1">Total Unit Allocation</p>
                <p className="font-bold text-gray-800">4.0% of Target Premium</p>
                <p className="text-xs text-gray-500">Total compensation pool for unit</p>
              </div>
              <div className="bg-white p-4 rounded border border-gray-200">
                <p className="text-xs font-semibold text-gray-500 uppercase tracking-wider mb-1">Personal Production (Director)</p>
                <p className="font-bold text-gray-800">4.0% of Target Premium</p>
                <p className="text-xs text-gray-500">For direct sales by Richard Keel</p>
              </div>
              <div className="bg-white p-4 rounded border border-gray-200">
                <p className="text-xs font-semibold text-gray-500 uppercase tracking-wider mb-1">Sub-Agent / Director Split</p>
                <p className="font-bold text-gray-800">3.0% Sub-Agent / 1.0% Override</p>
                <p className="text-xs text-gray-500">Default split (or custom tier per Exhibit A)</p>
              </div>
            </div>

            <div className="space-y-2 text-sm text-gray-700 mb-4 border-t pt-4">
              <p><strong>Payout Frequency:</strong> Monthly (disbursed by the 5th of each calendar month for the preceding month's production).</p>
              <p><strong>Direct Agency Disbursement:</strong> Vitannis directly processes and distributes payments to Richard Keel and all sub-agents, relieving the Sales Director of internal payroll administration.</p>
              <p><strong>Director Tier Placement Authority:</strong> Richard Keel maintains full discretion to assign individual sub-agents to specific commission rates (e.g., 2.5%, 3.5%). The Sales Director's override on each agent's production will adjust automatically to equal 4.0% minus the agent's assigned tier.</p>
            </div>

            <p className="text-xs italic text-gray-500 border-t pt-3">
              * Note: This schedule governs unit production and personal production. Corporate Direct Sales Agreements and institutional partnerships are excluded from this schedule and require a separate written Addendum.
            </p>
          </div>
        </section>

        {/* Addendum */}
        <section className="mt-16 print:break-before-page">
          <h2 className="text-2xl font-bold text-[#1a343c] border-b pb-2 mb-4 text-center">ADDENDUM: Distribution Agreements</h2>
          
          <div className="mb-6">
            <p className="mb-2 text-gray-700 leading-relaxed">
              This Addendum outlines separate Distribution Agreements, corporate direct sales arrangements, and institutional group contracts. Any compensation arrangements detailed herein are separate and distinct from the standard unit production detailed in Exhibit B.
            </p>
            <div className="p-3.5 my-3 bg-slate-50 border border-slate-200 rounded text-sm text-gray-700 leading-relaxed print:bg-transparent print:border-gray-300">
              <strong className="text-[#1a343c]">Ongoing Qualifications & Requirements:</strong> The ongoing standards and requirements set forth in <strong>Section 5</strong> of this Agreement to maintain entitlement to compensation and override payments (including maintaining an active Sales Director contract, actively engaging, mentoring, & supporting unit agent sales, maintaining an active insurance license in good standing, and adhering to all compliance and ethical standards) apply equally to all distribution agreements listed on this Addendum.
            </div>
            <p className="text-sm italic text-gray-600">
              Each distribution agreement listed below is an active addition to the primary Sales Director Agreement upon mutual execution by both Parties.
            </p>
          </div>

          <div className="space-y-8">
            {/* Record 1 - Fortis Strategic Partners */}
            <div className="border-2 border-dashed border-gray-300 p-6 rounded-lg print:border-solid print:border-gray-400 bg-white">
              <div className="flex justify-between items-center mb-4">
                <h3 className="font-bold text-[#1a343c]">Distribution Agreement Record #1</h3>
                <span className="text-xs bg-emerald-50 text-emerald-700 font-semibold border border-emerald-200 px-2 py-0.5 rounded">Active Schedule</span>
              </div>
              
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-4">
                <div>
                  <p className="text-sm text-gray-500 font-semibold mb-1">Entity / Distribution Group Name:</p>
                  <div className="border-b border-gray-400 pb-1 text-base font-bold text-gray-900">
                    Fortis Strategic Partners
                  </div>
                </div>
                <div>
                  <p className="text-sm text-gray-500 font-semibold mb-1">Effective Date:</p>
                  <div className="border-b border-gray-400 pb-1 text-base font-bold text-gray-900">
                    09/18/2026
                  </div>
                </div>
              </div>
              
              <div className="mb-4 mt-6">
                <p className="text-sm text-gray-500 font-semibold mb-1">Agreed Compensation & Override Terms:</p>
                <div className="border-b border-gray-400 pb-1 text-base font-semibold text-gray-900">
                  0.50% of Target Premium override
                </div>
                <p className="text-xs text-gray-600 mt-1.5 italic">
                  * 0.50% Target Premium override payable to Sales Director on qualifying Immediate Care Plan (ICP) business placed through Fortis Strategic Partners distribution channels.
                </p>
                <div className="border-b border-gray-400 h-4 mt-4"></div>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-8 mt-10">
                <div>
                  <p className="text-sm text-gray-500 mb-4">Vitannis Authorized Initial & Date</p>
                  <div className="border-b border-gray-400 w-40"></div>
                </div>
                <div>
                  <p className="text-sm text-gray-500 mb-4">Sales Director Initial & Date</p>
                  <div className="border-b border-gray-400 w-40"></div>
                </div>
              </div>
            </div>

            {/* Record 2 - Open Template */}
            <div className="border-2 border-dashed border-gray-300 p-6 rounded-lg print:border-solid print:border-gray-400">
              <div className="flex justify-between items-center mb-4">
                <h3 className="font-bold text-[#1a343c]">Distribution Agreement Record #2</h3>
                <span className="text-xs bg-gray-100 text-gray-600 px-2 py-1 rounded">Separate Schedule</span>
              </div>
              
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-4">
                <div>
                  <p className="text-sm text-gray-500 font-semibold mb-2">Entity / Distribution Group Name:</p>
                  <div className="border-b border-gray-400 h-6"></div>
                </div>
                <div>
                  <p className="text-sm text-gray-500 font-semibold mb-2">Effective Date:</p>
                  <div className="border-b border-gray-400 h-6"></div>
                </div>
              </div>
              
              <div className="mb-4 mt-6">
                <p className="text-sm text-gray-500 font-semibold mb-2">Agreed Compensation & Override Terms:</p>
                <div className="border-b border-gray-400 h-6 mt-4"></div>
                <div className="border-b border-gray-400 h-6 mt-6"></div>
                <div className="border-b border-gray-400 h-6 mt-6"></div>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-8 mt-10">
                <div>
                  <p className="text-sm text-gray-500 mb-4">Vitannis Authorized Initial & Date</p>
                  <div className="border-b border-gray-400 w-40"></div>
                </div>
                <div>
                  <p className="text-sm text-gray-500 mb-4">Sales Director Initial & Date</p>
                  <div className="border-b border-gray-400 w-40"></div>
                </div>
              </div>
            </div>
          </div>
        </section>

      </div>
      
      {/* Print Button */}
      <div className="fixed bottom-8 right-8 print:hidden">
        <button 
          onClick={() => window.print()}
          className="bg-[#1a343c] hover:bg-[#12242a] text-white font-bold py-3 px-6 rounded-full shadow-lg flex items-center space-x-2 transition-colors cursor-pointer"
        >
          <Printer className="w-5 h-5" />
          <span>Print / Save PDF</span>
        </button>
      </div>
    </div>
  );
}

